/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.udm2020di.widgets;

import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

import org.openide.util.WeakListeners;

import java.awt.EventQueue;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.SortedSet;
import java.util.TreeSet;

import javax.swing.JCheckBox;

import de.cismet.cids.custom.udm2020di.actions.remote.ExportAction;
import de.cismet.cids.custom.udm2020di.types.Parameter;

/**
 * DOCUMENT ME!
 *
 * @author   pd
 * @version  $Revision$, $Date$
 */
public class ExportParameterSelectionPanel extends javax.swing.JPanel implements ItemListener {

    //~ Instance fields --------------------------------------------------------

    protected transient org.jdesktop.beansbinding.BindingGroup bindingGroup;

    protected final transient SortedSet<Parameter> parameters = new TreeSet<Parameter>();

    protected final transient List selectedParameters = Collections.synchronizedList(new ArrayList());

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSelectAll;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbtnCsv;
    private javax.swing.JRadioButton rbtnShp;
    private javax.swing.JRadioButton rbtnXlsx;
    private javax.swing.JPanel selectionPanel;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form ParameterSelectionPanel.
     */
    public ExportParameterSelectionPanel() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();
        initComponents();
    }

    /**
     * Creates a new ParameterSelectionPanel object.
     *
     * @param  parameters  DOCUMENT ME!
     */
    public ExportParameterSelectionPanel(final Collection<Parameter> parameters) {
        this();
        this.setParameters(parameters);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        selectionPanel = new javax.swing.JPanel();
        actionPanel = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 5),
                new java.awt.Dimension(5, 5),
                new java.awt.Dimension(5, 5));
        btnReset = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 5),
                new java.awt.Dimension(5, 5),
                new java.awt.Dimension(5, 5));
        btnSelectAll = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
                new java.awt.Dimension(0, 0),
                new java.awt.Dimension(32767, 0));
        jLabel1 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 5),
                new java.awt.Dimension(5, 5),
                new java.awt.Dimension(5, 5));
        rbtnCsv = new javax.swing.JRadioButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 5),
                new java.awt.Dimension(5, 5),
                new java.awt.Dimension(5, 5));
        rbtnXlsx = new javax.swing.JRadioButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 5),
                new java.awt.Dimension(5, 5),
                new java.awt.Dimension(5, 5));
        rbtnShp = new javax.swing.JRadioButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5),
                javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createTitledBorder(
                        org.openide.util.NbBundle.getMessage(
                            ExportParameterSelectionPanel.class,
                            "ExportParameterSelectionPanel.border.insideBorder.outsideBorder.title")),
                    javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)))); // NOI18N
        setMinimumSize(new java.awt.Dimension(500, 100));
        setLayout(new java.awt.BorderLayout(5, 5));

        selectionPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        selectionPanel.setLayout(new java.awt.GridLayout(0, 3, 5, 5));
        add(selectionPanel, java.awt.BorderLayout.CENTER);

        actionPanel.setLayout(new javax.swing.BoxLayout(actionPanel, javax.swing.BoxLayout.LINE_AXIS));

        btnExport.setText(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.btnExport.text"));          // NOI18N
        btnExport.setActionCommand(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.btnExport.actionCommand")); // NOI18N
        btnExport.setAutoscrolls(true);
        actionPanel.add(btnExport);
        actionPanel.add(filler2);

        btnReset.setText(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.btnReset.text"));          // NOI18N
        btnReset.setActionCommand(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.btnReset.actionCommand")); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnResetActionPerformed(evt);
                }
            });
        actionPanel.add(btnReset);
        actionPanel.add(filler5);

        btnSelectAll.setText(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.btnSelectAll.text")); // NOI18N
        btnSelectAll.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    btnSelectAllActionPerformed(evt);
                }
            });
        actionPanel.add(btnSelectAll);
        actionPanel.add(filler1);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.jLabel1.text")); // NOI18N
        actionPanel.add(jLabel1);
        actionPanel.add(filler3);

        buttonGroup1.add(rbtnCsv);
        rbtnCsv.setSelected(true);
        rbtnCsv.setText(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.rbtnCsv.text"));        // NOI18N
        rbtnCsv.setToolTipText(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.rbtnCsv.toolTipText")); // NOI18N
        rbtnCsv.addItemListener(new java.awt.event.ItemListener() {

                @Override
                public void itemStateChanged(final java.awt.event.ItemEvent evt) {
                    exportFormatSelected(evt);
                }
            });
        actionPanel.add(rbtnCsv);
        actionPanel.add(filler4);

        buttonGroup1.add(rbtnXlsx);
        rbtnXlsx.setText(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.rbtnXlsx.text"));        // NOI18N
        rbtnXlsx.setToolTipText(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.rbtnXlsx.toolTipText")); // NOI18N
        rbtnXlsx.addItemListener(new java.awt.event.ItemListener() {

                @Override
                public void itemStateChanged(final java.awt.event.ItemEvent evt) {
                    exportFormatSelected(evt);
                }
            });
        actionPanel.add(rbtnXlsx);
        actionPanel.add(filler6);

        buttonGroup1.add(rbtnShp);
        rbtnShp.setText(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.rbtnShp.text"));        // NOI18N
        rbtnShp.setToolTipText(org.openide.util.NbBundle.getMessage(
                ExportParameterSelectionPanel.class,
                "ExportParameterSelectionPanel.rbtnShp.toolTipText")); // NOI18N
        rbtnShp.addItemListener(new java.awt.event.ItemListener() {

                @Override
                public void itemStateChanged(final java.awt.event.ItemEvent evt) {
                    exportFormatSelected(evt);
                }
            });
        actionPanel.add(rbtnShp);

        add(actionPanel, java.awt.BorderLayout.SOUTH);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnResetActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnResetActionPerformed

        if ((this.parameters != null) && !this.parameters.isEmpty()) {
            for (final Parameter parameter : this.parameters) {
                parameter.setSelected(false);
            }
        }
    } //GEN-LAST:event_btnResetActionPerformed

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void exportFormatSelected(final java.awt.event.ItemEvent evt) { //GEN-FIRST:event_exportFormatSelected
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            final ExportAction exportAction = this.getExportAction();
            if (exportAction != null) {
                if (evt.getItemSelectable() == this.rbtnCsv) {
                    exportAction.setExportFormat(
                        de.cismet.cids.custom.udm2020di.serveractions.AbstractExportAction.PARAM_EXPORTFORMAT_CSV);
                } else if (evt.getItemSelectable() == this.rbtnXlsx) {
                    exportAction.setExportFormat(
                        de.cismet.cids.custom.udm2020di.serveractions.AbstractExportAction.PARAM_EXPORTFORMAT_XLSX);
                } else if (evt.getItemSelectable() == this.rbtnShp) {
                    exportAction.setExportFormat(
                        de.cismet.cids.custom.udm2020di.serveractions.AbstractExportAction.PARAM_EXPORTFORMAT_SHP);
                }
            }
        }
    } //GEN-LAST:event_exportFormatSelected

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void btnSelectAllActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_btnSelectAllActionPerformed
        for (final Parameter parameter : this.parameters) {
            parameter.setSelected(true);
        }
    }                                                                                //GEN-LAST:event_btnSelectAllActionPerformed

    /**
     * Get the value of parameters.
     *
     * @return  the value of parameters
     */
    public final Collection<Parameter> getParameters() {
        return parameters;
    }

    /**
     * Set the value of parameters.
     *
     * @param  parameters  new value of parameters
     */
    public final void setParameters(final Collection<Parameter> parameters) {
        this.parameters.addAll(parameters);

        final Runnable r = new Runnable() {

                @Override
                public void run() {
                    ExportParameterSelectionPanel.this.selectionPanel.removeAll();
                    bindingGroup.unbind();
                    if ((parameters != null) && !ExportParameterSelectionPanel.this.parameters.isEmpty()) {
                        for (final Parameter parameter : ExportParameterSelectionPanel.this.parameters) {
                            final JCheckBox checkBox = new JCheckBox(parameter.getParameterName());
                            checkBox.addItemListener(WeakListeners.create(
                                    ItemListener.class,
                                    ExportParameterSelectionPanel.this,
                                    checkBox));
                            ExportParameterSelectionPanel.this.selectionPanel.add(checkBox);
                            final Binding binding = Bindings.createAutoBinding(
                                    AutoBinding.UpdateStrategy.READ_WRITE,
                                    parameter,
                                    ELProperty.create("${selected}"),
                                    checkBox,
                                    BeanProperty.create("selected"));
                            bindingGroup.addBinding(binding);
                        }

                        bindingGroup.bind();
                    }
                }
            };

        if (EventQueue.isDispatchThread()) {
            r.run();
        } else {
            EventQueue.invokeLater(r);
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public final Collection<Parameter> getSelectedParameters() {
        synchronized (selectedParameters) {
            selectedParameters.clear();
            if ((this.parameters != null) && !this.parameters.isEmpty()) {
                for (final Parameter parameter : this.parameters) {
                    if (parameter.isSelected()) {
                        selectedParameters.add(parameter);
                    }
                }
            }
        }
        return selectedParameters;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  exportAction  DOCUMENT ME!
     */
    public void setExportAction(final ExportAction exportAction) {
        btnExport.setAction(exportAction);
    }

    /**
     * Get the value of exportAction.
     *
     * @return  the value of exportAction
     */
    public ExportAction getExportAction() {
        return ((btnExport.getAction() != null)
                        && ExportAction.class.isAssignableFrom(btnExport.getAction().getClass()))
            ? (ExportAction)btnExport.getAction() : null;
    }

    @Override
    public void itemStateChanged(final ItemEvent e) {
        final Collection<Parameter> selParameters = this.getSelectedParameters();

        if (selParameters.isEmpty()) {
            this.btnExport.getAction().setEnabled(false);
            this.btnReset.setEnabled(false);
        } else {
            this.btnExport.getAction().setEnabled(true);
            this.btnReset.setEnabled(true);
        }

        if (selParameters.size() == this.parameters.size()) {
            this.btnSelectAll.setEnabled(false);
        } else {
            this.btnSelectAll.setEnabled(true);
        }
    }
}
