/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.cids.custom.udm2020di.widgets;

import org.apache.log4j.BasicConfigurator;
import org.apache.log4j.Logger;

import java.awt.Dimension;
import java.awt.GridBagConstraints;

import java.util.AbstractMap.SimpleEntry;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JButton;
import javax.swing.JFrame;

import de.cismet.cids.custom.udm2020di.indeximport.OracleImport;
import de.cismet.cids.custom.udm2020di.types.AggregationValue;
import de.cismet.cids.custom.udm2020di.types.AggregationValues;
import de.cismet.cids.custom.udm2020di.types.boris.Standort;

/**
 * DOCUMENT ME!
 *
 * @author   pd
 * @version  $Revision$, $Date$
 */
public class MaxParameterValueSelectionPanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    protected final transient Collection<MaxParameterValuePanel> parameterValuePanels =
        new ArrayList<MaxParameterValuePanel>();

    protected transient Collection<AggregationValue> aggregationValues;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMeButton;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form MaxValueSelectionPanel.
     */
    public MaxParameterValueSelectionPanel() {
        initComponents();
    }

    /**
     * Creates a new MaxParameterValueSelectionPanel object.
     *
     * @param  aggregationValues  DOCUMENT ME!
     */
    public MaxParameterValueSelectionPanel(final Collection<AggregationValue> aggregationValues) {
        this();
        this.setAggregationValues(aggregationValues);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @param  aggregationValues  DOCUMENT ME!
     */
    public final void setAggregationValues(final Collection<AggregationValue> aggregationValues) {
        this.aggregationValues = aggregationValues;

        if ((aggregationValues != null) && !aggregationValues.isEmpty()) {
            this.addParameterValuePanel();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        final java.awt.GridBagConstraints gridBagConstraints;

        addMeButton = new javax.swing.JButton();

        addMeButton.setFont(new java.awt.Font("Tahoma", 1, 14));      // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(addMeButton, "+"); // NOI18N
        addMeButton.setMargin(new java.awt.Insets(2, 6, 2, 6));
        addMeButton.addActionListener(new java.awt.event.ActionListener() {

                @Override
                public void actionPerformed(final java.awt.event.ActionEvent evt) {
                    addMeButtonActionPerformed(evt);
                }
            });

        setLayout(new java.awt.GridBagLayout());
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void addMeButtonActionPerformed(final java.awt.event.ActionEvent evt) { //GEN-FIRST:event_addMeButtonActionPerformed
        this.addParameterValuePanel();
    }                                                                               //GEN-LAST:event_addMeButtonActionPerformed

    /**
     * DOCUMENT ME!
     */
    public void reset() {
        this.parameterValuePanels.clear();
        this.removeAll();
        this.initComponents();
    }

    /**
     * DOCUMENT ME!
     */
    protected void addParameterValuePanel() {
        remove(addMeButton);

        final GridBagConstraints gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.0;
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = GridBagConstraints.RELATIVE;

        final MaxParameterValuePanel parameterValuePanel = new MaxParameterValuePanel(aggregationValues);
        this.add(parameterValuePanel, gridBagConstraints);
        this.parameterValuePanels.add(parameterValuePanel);

        final JButton removeMeButton = new javax.swing.JButton("-");
        removeMeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        removeMeButton.setMargin(new java.awt.Insets(2, 8, 2, 8));
        if (this.parameterValuePanels.size() > 1) {
            removeMeButton.addActionListener(new java.awt.event.ActionListener() {

                    @Override
                    public void actionPerformed(final java.awt.event.ActionEvent evt) {
                        parameterValuePanels.remove(parameterValuePanel);
                        remove(parameterValuePanel);
                        remove(removeMeButton);
                        removeMeButton.removeActionListener(this);
                        validate();
                    }
                });
        } else {
            removeMeButton.setEnabled(false);
        }

        gridBagConstraints.gridx = 1;
        gridBagConstraints.weightx = 1.0;
        this.add(removeMeButton, gridBagConstraints);

        gridBagConstraints.gridx = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        this.add(addMeButton, gridBagConstraints);

        validate();
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public Map<String, Float> getValues() {
        final Map<String, Float> values = new HashMap<String, Float>();
        for (final MaxParameterValuePanel parameterValuePanel : this.parameterValuePanels) {
            final SimpleEntry<String, Float> value = parameterValuePanel.getValue();
            values.put(value.getKey(), value.getValue());
        }

        return values;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  args  DOCUMENT ME!
     */
    public static void main(final String[] args) {
        try {
            BasicConfigurator.configure();
            final Standort borisStandort = OracleImport.JSON_MAPPER.readValue(
                    MaxParameterValueSelectionPanel.class.getResourceAsStream(
                        "/de/cismet/cids/custom/udm2020di/testing/BorisStandort.json"),
                    Standort.class);

            final AggregationValues aggregationValues = new AggregationValues(borisStandort.getAggregationValues());

            aggregationValues.addAll(borisStandort.getAggregationValues());
            aggregationValues.addAll(borisStandort.getAggregationValues());

            final MaxParameterValueSelectionPanel panel = new MaxParameterValueSelectionPanel(
                    borisStandort.getAggregationValues());

            final JFrame frame = new JFrame("MaxParameterValueSelectionPanel");
            frame.getContentPane().add(panel);
            frame.getContentPane().setPreferredSize(new Dimension(600, 400));
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.pack();
            frame.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MaxParameterValueSelectionPanel.class).fatal(ex.getMessage(), ex);
            System.exit(1);
        }
    }
}
