/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.udm2020di.widgets.eprtr;

import java.awt.Dimension;

import java.util.Collection;

import javax.swing.Box;

import de.cismet.cids.custom.udm2020di.types.eprtr.Activity;

/**
 * DOCUMENT ME!
 *
 * @author   pd
 * @version  $Revision$, $Date$
 */
public class ActivitiesPanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    private String notificationPeriod;

    private Collection<Activity> activities;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.cids.custom.udm2020di.search.CustomMaxValuesSearchPanel customMaxValuesSearchPanel1;
    private javax.swing.Box.Filler filler1;
    private de.cismet.cids.custom.udm2020di.widgets.MapPanel mapPanel1;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form ActivitiesPanel.
     */
    public ActivitiesPanel() {
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * Get the value of notificationPeriod.
     *
     * @return  the value of notificationPeriod
     */
    public String getNotificationPeriod() {
        return notificationPeriod;
    }

    /**
     * Set the value of notificationPeriod.
     *
     * @param  notificationPeriod  new value of notificationPeriod
     */
    public void setNotificationPeriod(final String notificationPeriod) {
        this.notificationPeriod = notificationPeriod;
        initComponents();
    }

    /**
     * Get the value of activities.
     *
     * @return  the value of activities
     */
    public Collection<Activity> getActivities() {
        return activities;
    }

    /**
     * Set the value of activities.
     *
     * @param  activities  new value of activities
     */
    public void setActivities(final Collection<Activity> activities) {
        this.activities = activities;

        int i = 0;
        for (final Activity activity : this.activities) {
            i++;
            final ActivityPanel activityPanel = new ActivityPanel();
            activityPanel.setActivity(activity);
            this.add(activityPanel);
            if (i < this.activities.size()) {
                this.add(new javax.swing.JSeparator());
            }
        }

        this.add(Box.createVerticalGlue());
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Override
    public Dimension getMaximumSize() {
        return new Dimension(super.getMaximumSize().width, getPreferredSize().height);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        customMaxValuesSearchPanel1 = new de.cismet.cids.custom.udm2020di.search.CustomMaxValuesSearchPanel();
        mapPanel1 = new de.cismet.cids.custom.udm2020di.widgets.MapPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
                new java.awt.Dimension(0, 0),
                new java.awt.Dimension(32767, 32767));

        setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5),
                javax.swing.BorderFactory.createTitledBorder("Aktivitäten in " + this.getNotificationPeriod())));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
        add(filler1);
    } // </editor-fold>//GEN-END:initComponents
}
