/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.udm2020di.widgets.eprtr;

import java.awt.Dimension;
import java.awt.EventQueue;

import de.cismet.cids.custom.udm2020di.types.eprtr.Activity;

/**
 * DOCUMENT ME!
 *
 * @author   Pascal Dihé
 * @version  $Revision$, $Date$
 */
public class ActivityPanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    private Activity activity;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JLabel lblOpertingHours;
    private javax.swing.JLabel lblOpertingHoursValue;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProductValue;
    private javax.swing.JLabel lblProductionVolumne;
    private javax.swing.JLabel lblProductionVolumneValue;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form AddressPanel.
     */
    public ActivityPanel() {
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * Get the value of address.
     *
     * @return  the value of address
     */
    public Activity getActivity() {
        return activity;
    }

    /**
     * Set the value of address.
     *
     * @param  activity  new value of address
     */
    public void setActivity(final Activity activity) {
        final Runnable r = new Runnable() {

                @Override
                public void run() {
                    ActivityPanel.this.activity = activity;
                    ActivityPanel.this.initComponents();

                    lblProduct.setVisible((activity.getProduct() != null)
                                && !activity.getProduct().isEmpty());
                    lblProductValue.setVisible((activity.getProduct() != null)
                                && !activity.getProduct().isEmpty());
                    lblProductionVolumne.setVisible(activity.getProductionVolume() > 0);
                    lblProductionVolumneValue.setVisible(activity.getProductionVolume() > 0);
                    lblOpertingHours.setVisible(activity.getOperatingHours() > 0);
                    lblOpertingHoursValue.setVisible(activity.getOperatingHours() > 0);
                }
            };

        if (EventQueue.isDispatchThread()) {
            r.run();
        } else {
            EventQueue.invokeLater(r);
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public String getActivityDescription() {
        if (this.activity != null) {
            return "<html>" + this.activity.getName() + "</html>";
        } else {
            return "";
        }
    }

    @Override
    public Dimension getMaximumSize() {
        return new Dimension(super.getMaximumSize().width, getPreferredSize().height);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        lblProduct = new javax.swing.JLabel();
        lblProductValue = new javax.swing.JLabel();
        lblProductionVolumne = new javax.swing.JLabel();
        lblProductionVolumneValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblOpertingHours = new javax.swing.JLabel();
        lblOpertingHoursValue = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(
            lblProduct,
            org.openide.util.NbBundle.getMessage(ActivityPanel.class, "ActivityPanel.lblProduct.text")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${activity.product}"),
                lblProductValue,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("null");
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(
            lblProductionVolumne,
            org.openide.util.NbBundle.getMessage(ActivityPanel.class, "ActivityPanel.lblProductionVolumne.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${activity.productionVolume}"),
                lblProductionVolumneValue,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel1.setMaximumSize(new java.awt.Dimension(500, 2147483647));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${activityDescription}"),
                jLabel1,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue(" ");
        binding.setSourceUnreadableValue(" ");
        bindingGroup.addBinding(binding);

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
        setMaximumSize(new java.awt.Dimension(600, 2147483647));
        setLayout(new java.awt.GridBagLayout());

        jTextArea.setEditable(false);
        jTextArea.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        jTextArea.setColumns(25);
        jTextArea.setLineWrap(true);
        jTextArea.setRows(3);
        jTextArea.setWrapStyleWord(true);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${activity.name}"),
                jTextArea,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue(" ");
        binding.setSourceUnreadableValue(" ");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jTextArea, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel3,
            org.openide.util.NbBundle.getMessage(ActivityPanel.class, "ActivityPanel.jLabel3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        add(jLabel3, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${activity.mnemonic}"),
                jLabel4,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("null");
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(jLabel4, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            jLabel5,
            org.openide.util.NbBundle.getMessage(ActivityPanel.class, "ActivityPanel.jLabel5.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        add(jLabel5, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${activity.primaryActivity}"),
                jLabel6,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("null");
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(jLabel6, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(
            lblOpertingHours,
            org.openide.util.NbBundle.getMessage(ActivityPanel.class, "ActivityPanel.lblOpertingHours.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        add(lblOpertingHours, gridBagConstraints);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(
                org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_ONCE,
                this,
                org.jdesktop.beansbinding.ELProperty.create("${activity.operatingHours}"),
                lblOpertingHoursValue,
                org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setSourceNullValue("null");
        binding.setSourceUnreadableValue("null");
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(lblOpertingHoursValue, gridBagConstraints);

        bindingGroup.bind();
    } // </editor-fold>//GEN-END:initComponents
}
