/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.udm2020di.widgets.eprtr;

import java.util.Collection;

import javax.swing.Box;

import de.cismet.cids.custom.udm2020di.types.eprtr.Activity;
import de.cismet.cids.custom.udm2020di.types.eprtr.Notification;

/**
 * DOCUMENT ME!
 *
 * @author   pd
 * @version  $Revision$, $Date$
 */
public class NotificationsPanel extends javax.swing.JPanel {

    //~ Instance fields --------------------------------------------------------

    private String notificationPeriod;

    private Collection<Notification> notifications;

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form ActivitiesPanel.
     */
    public NotificationsPanel() {
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * Get the value of activities.
     *
     * @return  the value of activities
     */
    public Collection<Notification> getNotifications() {
        return notifications;
    }

    /**
     * Set the value of activities.
     *
     * @param  notifications  new value of activities
     */
    public void setNotifications(final Collection<Notification> notifications) {
        this.notifications = notifications;

        for (final Notification notification : this.notifications) {
            final NotificationPanel notificationPanel = new NotificationPanel();
            notificationPanel.setNotification(notification);
            this.add(notificationPanel);
        }

        this.add(Box.createGlue());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
