/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.udm2020di.featurerenderer;

import org.apache.log4j.Logger;

import java.awt.Image;

import de.cismet.cids.featurerenderer.CustomCidsFeatureRenderer;

import de.cismet.cismap.commons.features.ScaleAwareFeatureRenderer;
import de.cismet.cismap.commons.gui.featurecontrolwidget.CoordHider;
import de.cismet.cismap.commons.gui.piccolo.FeatureAnnotationSymbol;

import static de.cismet.cids.custom.udm2020di.treeicons.BorisSiteIconFactory.BORIS_SITE_ICON;

/**
 * DOCUMENT ME!
 *
 * @author   Pascal Dihé
 * @version  0.1
 */
public class BorisSiteFeatureRenderer extends CustomCidsFeatureRenderer implements ScaleAwareFeatureRenderer,
    CoordHider {

    //~ Static fields/initializers ---------------------------------------------

    private static final transient Logger LOG = Logger.getLogger(BorisSiteFeatureRenderer.class);

    //~ Instance fields --------------------------------------------------------

    private final transient Image borisSitePointSymbolUnselected;

    //~ Constructors -----------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form TimeseriesFeatureRenderer.
     */
    public BorisSiteFeatureRenderer() {
        initComponents();
        borisSitePointSymbolUnselected = BORIS_SITE_ICON.getImage();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setMaximumSize(new java.awt.Dimension(300, 200));
        setMinimumSize(new java.awt.Dimension(300, 200));
        setPreferredSize(new java.awt.Dimension(300, 200));
        setLayout(new java.awt.BorderLayout());
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     */
    @Override
    public void assign() {
    }
    /**
     * TODO: not necessarily only rain symbol, symbol selection must be cidsbean dependent
     *
     * @return  DOCUMENT ME!
     */
    @Override
    public FeatureAnnotationSymbol getPointSymbol() {
        if (borisSitePointSymbolUnselected == null) {
            return super.getPointSymbol();
        } else {
            return FeatureAnnotationSymbol.newCustomSweetSpotFeatureAnnotationSymbol(
                    borisSitePointSymbolUnselected,
                    null,
                    0.5,
                    0.9);
        }
    }

    @Override
    public int getMinScale() {
        return Integer.MAX_VALUE;
    }

    @Override
    public int getMaxScale() {
        return 126000;
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Override
    public float getTransparency() {
        return 0.9f;
    }

    @Override
    public String getAlternativeName() {
        return cidsBean.getProperty("src_standort_pk").toString();
    }
}
