/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.cids.custom.udm2020di.objectrenderer;

import org.apache.log4j.Logger;

import java.awt.Dimension;

import javax.swing.Box;
import javax.swing.JLabel;

import de.cismet.cids.custom.udm2020di.AbstractCidsBeanRenderer;
import de.cismet.cids.custom.udm2020di.indeximport.OracleImport;
import de.cismet.cids.custom.udm2020di.types.boris.Standort;
import de.cismet.cids.custom.udm2020di.types.boris.Standortparameter;

/**
 * DOCUMENT ME!
 *
 * @author   pd
 * @version  $Revision$, $Date$
 */
public class BorisSiteRenderer extends AbstractCidsBeanRenderer {

    //~ Static fields/initializers ---------------------------------------------

    protected static final Logger logger = Logger.getLogger(BorisSiteRenderer.class);

    //~ Instance fields --------------------------------------------------------

    private Standort borisStandort;

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form BorisSiteRenderer.
     */
    public BorisSiteRenderer() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * Get the value of borisStandort.
     *
     * @return  the value of borisStandort
     */
    public Standort getBorisStandort() {
        return borisStandort;
    }

    /**
     * Set the value of borisStandort.
     *
     * @param  borisStandort  new value of borisStandort
     */
    public void setBorisStandort(final Standort borisStandort) {
        this.borisStandort = borisStandort;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    protected void init() {
        try {
            this.borisStandort = OracleImport.JSON_MAPPER.readValue(this.getCidsBean().getProperty("src_content")
                            .toString(),
                    Standort.class);
        } catch (Exception ex) {
            logger.error("could not deserialize boris Standort JSON: " + ex.getMessage(), ex);
        }

        // final String[] propertyNames = this.getCidsBean().getPropertyNames();
        for (final Standortparameter standortparameter : borisStandort.getStandortparameter()) {
            this.add(new JLabel(standortparameter.getName() + ": "));
            this.add(Box.createRigidArea(new Dimension(10, 0)));
            this.add(new JLabel(standortparameter.getWert()));
            this.add(Box.createHorizontalGlue());

//            final Object property = this.getCidsBean().getProperty(propertyName);
//            if (property != null) {
//                this.add(new JLabel(propertyName + ": "));
//                this.add(Box.createRigidArea(new Dimension(10, 0)));
//                this.add(new JLabel(property.toString()));
//                this.add(Box.createHorizontalGlue());
//            }

        }
    }
}
