/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.cids.custom.udm2020di.objectrenderer;

import java.awt.Dimension;

import javax.swing.Box;
import javax.swing.JLabel;

import de.cismet.cids.custom.udm2020di.AbstractCidsBeanRenderer;

/**
 * DOCUMENT ME!
 *
 * @author   pd
 * @version  $Revision$, $Date$
 */
public class BorisSampleRenderer extends AbstractCidsBeanRenderer {

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form BorisSiteRenderer.
     */
    public BorisSampleRenderer() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    } // </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    protected void init() {
        final String[] propertyNames = this.getCidsBean().getPropertyNames();
        for (final String propertyName : propertyNames) {
            final Object property = this.getCidsBean().getProperty(propertyName);
            if (property != null) {
                this.add(new JLabel(propertyName + ": "));
                this.add(Box.createRigidArea(new Dimension(10, 0)));
                this.add(new JLabel(property.toString()));
                this.add(Box.createHorizontalGlue());
            }
        }
    }
}
