/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.udm2020di.objectrenderer;

import org.apache.log4j.Logger;

import java.awt.EventQueue;

import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.TreeSet;

import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

import de.cismet.cids.custom.udm2020di.actions.remote.EprtrExportAction;
import de.cismet.cids.custom.udm2020di.actions.remote.EprtrVisualisationAction;
import de.cismet.cids.custom.udm2020di.actions.remote.VisualisationAction;
import de.cismet.cids.custom.udm2020di.indeximport.OracleImport;
import de.cismet.cids.custom.udm2020di.tools.DefaultRendererConfigurationHelper;
import de.cismet.cids.custom.udm2020di.tools.NameListCellRenderer;
import de.cismet.cids.custom.udm2020di.types.AggregationValue;
import de.cismet.cids.custom.udm2020di.types.AggregationValues;
import de.cismet.cids.custom.udm2020di.types.Parameter;
import de.cismet.cids.custom.udm2020di.types.eprtr.Installation;
import de.cismet.cids.custom.udm2020di.widgets.ExportParameterSelectionPanel;

import de.cismet.cids.dynamics.CidsBean;

import de.cismet.cids.tools.metaobjectrenderer.CidsBeanAggregationRendererPanel;

import static de.cismet.cids.custom.udm2020di.objectrenderer.EprtrInstallationRenderer.DATE_FORMAT;

/**
 * DOCUMENT ME!
 *
 * @author   Pascal Dihé
 * @version  $Revision$, $Date$
 */
public class EprtrInstallationAggregationRenderer extends CidsBeanAggregationRendererPanel
        implements ConfigurableRenderer {

    //~ Static fields/initializers ---------------------------------------------

    protected static final Logger LOGGER = Logger.getLogger(EprtrInstallationAggregationRenderer.class);

    //~ Instance fields --------------------------------------------------------

    private transient Collection<CidsBean> cidsBeans;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel exportPanel;
    private javax.swing.JPanel featureSelectionPanel;
    private javax.swing.JList featuresList;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private de.cismet.cids.custom.udm2020di.widgets.MapPanel mapPanel;
    private javax.swing.JScrollPane messwerteScrollPane;
    private javax.swing.JTable messwerteTable;
    private de.cismet.cids.custom.udm2020di.widgets.ParameterPanel parameterPanel;
    private de.cismet.cids.custom.udm2020di.widgets.ExportParameterSelectionPanel parameterSelectionPanel;
    private de.cismet.cids.custom.udm2020di.widgets.eprtr.EprtrVisualisationPanel visualisationPanel;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form EprtrSiteRenderer.
     */
    public EprtrInstallationAggregationRenderer() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * Get the value of cidsBeans.
     *
     * @return  the value of cidsBeans
     */
    @Override
    public Collection<CidsBean> getCidsBeans() {
        return cidsBeans;
    }

    /**
     * Set the value of cidsBeans.
     *
     * @param  cidsBeans  new value of cidsBeans
     */
    @Override
    public void setCidsBeans(final Collection<CidsBean> cidsBeans) {
        this.cidsBeans = cidsBeans;
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        parameterPanel = new de.cismet.cids.custom.udm2020di.widgets.ParameterPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        infoPanel = new javax.swing.JPanel();
        mapPanel = new de.cismet.cids.custom.udm2020di.widgets.MapPanel();
        featureSelectionPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        featuresList = new javax.swing.JList();
        messwerteScrollPane = new javax.swing.JScrollPane();
        messwerteTable = new javax.swing.JTable();
        exportPanel = new javax.swing.JPanel();
        parameterSelectionPanel = new ExportParameterSelectionPanel(true);
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
                new java.awt.Dimension(0, 0),
                new java.awt.Dimension(32767, 32767));
        visualisationPanel = new de.cismet.cids.custom.udm2020di.widgets.eprtr.EprtrVisualisationPanel();

        parameterPanel.setMinimumSize(new java.awt.Dimension(200, 300));

        setLayout(new java.awt.BorderLayout());

        jTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        infoPanel.setLayout(new java.awt.GridBagLayout());

        mapPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5),
                javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createTitledBorder(
                        org.openide.util.NbBundle.getMessage(
                            EprtrInstallationAggregationRenderer.class,
                            "EprtrInstallationAggregationRenderer.mapPanel.border.insideBorder.outsideBorder.title")),
                    javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)))); // NOI18N
        mapPanel.setMinimumSize(new java.awt.Dimension(300, 500));
        mapPanel.setPreferredSize(new java.awt.Dimension(300, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 1.0;
        infoPanel.add(mapPanel, gridBagConstraints);

        featureSelectionPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5),
                javax.swing.BorderFactory.createCompoundBorder(
                    javax.swing.BorderFactory.createTitledBorder(
                        org.openide.util.NbBundle.getMessage(
                            EprtrInstallationAggregationRenderer.class,
                            "EprtrInstallationAggregationRenderer.featureSelectionPanel.border.insideBorder.outsideBorder.title")),
                    javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)))); // NOI18N
        featureSelectionPanel.setMinimumSize(new java.awt.Dimension(300, 300));
        featureSelectionPanel.setLayout(new java.awt.GridLayout(1, 0));

        featuresList.setModel(new javax.swing.AbstractListModel() {

                String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

                @Override
                public int getSize() {
                    return strings.length;
                }
                @Override
                public Object getElementAt(final int i) {
                    return strings[i];
                }
            });
        featuresList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        featuresList.setCellRenderer(new NameListCellRenderer());
        featuresList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {

                @Override
                public void valueChanged(final javax.swing.event.ListSelectionEvent evt) {
                    featuresListValueChanged(evt);
                }
            });
        jScrollPane2.setViewportView(featuresList);

        featureSelectionPanel.add(jScrollPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 1.0;
        infoPanel.add(featureSelectionPanel, gridBagConstraints);

        jTabbedPane.addTab(org.openide.util.NbBundle.getMessage(
                EprtrInstallationAggregationRenderer.class,
                "EprtrInstallationAggregationRenderer.infoPanel.TabConstraints.tabTitle_1"),
            infoPanel); // NOI18N

        messwerteTable.setBorder(javax.swing.BorderFactory.createLineBorder(
                javax.swing.UIManager.getDefaults().getColor("Table.dropLineColor")));
        messwerteTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                    "Art der Freisetzung",
                    "Schadstoff",
                    "Minimalwert [kg/J]",
                    "in Periode",
                    "Maximalwert [kg/J]",
                    "in Periode"
                }) {

                Class[] types = new Class[] {
                        java.lang.String.class,
                        java.lang.String.class,
                        java.lang.Float.class,
                        java.lang.String.class,
                        java.lang.Float.class,
                        java.lang.String.class
                    };
                boolean[] canEdit = new boolean[] { false, false, false, false, false, false };

                @Override
                public Class getColumnClass(final int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(final int rowIndex, final int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
        messwerteTable.setFillsViewportHeight(true);
        messwerteTable.setPreferredSize(new java.awt.Dimension(300, 500));
        messwerteTable.setRequestFocusEnabled(false);
        messwerteScrollPane.setViewportView(messwerteTable);

        jTabbedPane.addTab("Aggregierte Messwerte", messwerteScrollPane);

        exportPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        exportPanel.add(parameterSelectionPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        exportPanel.add(filler2, gridBagConstraints);

        jTabbedPane.addTab(org.openide.util.NbBundle.getMessage(
                EprtrInstallationAggregationRenderer.class,
                "EprtrInstallationAggregationRenderer.exportPanel.TabConstraints.tabTitle_1_1"),
            exportPanel); // NOI18N
        jTabbedPane.addTab("Datenvisualisierung", visualisationPanel);

        add(jTabbedPane, java.awt.BorderLayout.CENTER);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void featuresListValueChanged(final javax.swing.event.ListSelectionEvent evt) { //GEN-FIRST:event_featuresListValueChanged
        if (!evt.getValueIsAdjusting()) {
            this.mapPanel.gotoCidsBean((CidsBean)this.featuresList.getSelectedValue());
        }
    }                                                                                       //GEN-LAST:event_featuresListValueChanged

    /**
     * DOCUMENT ME!
     */
    protected void init() {
        if ((cidsBeans != null) && !cidsBeans.isEmpty()) {
            LOGGER.info("processing " + cidsBeans.size() + "cids beans");
            final Runnable r = new Runnable() {

                    @Override
                    public void run() {
                        mapPanel.setCidsBeans(cidsBeans);

                        final Collection<Installation> installations = new ArrayList<Installation>();
                        final TreeSet<Parameter> parametersSet = new TreeSet<Parameter>();
                        final HashMap<Long, String> objectIds = new HashMap<Long, String>();
                        final TreeSet<Long> installationPks = new TreeSet<Long>();
                        final DefaultListModel listModel = new DefaultListModel();
                        final AggregationValues aggregationValues = new AggregationValues();

                        for (final CidsBean cidsBean : cidsBeans) {
                            listModel.addElement(cidsBean);
                            objectIds.put(cidsBean.getPrimaryKeyValue().longValue(),
                                cidsBean.getProperty("name").toString());

                            try {
                                final Installation installation = OracleImport.JSON_MAPPER.readValue(
                                        cidsBean.getProperty("src_content").toString(),
                                        Installation.class);
                                installations.add(installation);

                                final ArrayList<String> parameterNames = new ArrayList<String>(
                                        installation.getReleaseParameters().size());
                                for (final Parameter probenparameter : installation.getReleaseParameters()) {
                                    parameterNames.add(probenparameter.getParameterName());
                                }

                                installationPks.add(installation.getErasId());

                                parametersSet.addAll(installation.getReleaseParameters());

                                aggregationValues.addAll(installation.getAggregationValues());
                            } catch (Exception ex) {
                                LOGGER.error("could not deserialize eprtr Installation JSON: " + ex.getMessage(), ex);
                            }
                        }

                        featuresList.setModel(listModel);
                        // parameterPanel.setParameterNames(parameterNamesSet);

                        // Export Tab
                        parameterSelectionPanel.setParameters(parametersSet);
                        final EprtrExportAction exportAction = new EprtrExportAction(
                                parameterSelectionPanel.getSelectedParameters(),
                                objectIds,
                                installationPks);
                        parameterSelectionPanel.setExportAction(exportAction);

                        // Messwerte Tab -------------------------------
                        final DefaultTableModel tableModel = (DefaultTableModel)messwerteTable.getModel();
                        for (final AggregationValue aggregationValue : aggregationValues) {
                            final Object[] rowData = new Object[] {
                                    aggregationValue.getReleaseType(),
                                    aggregationValue.getName(),
                                    aggregationValue.getMinValue(),
                                    DATE_FORMAT.format(aggregationValue.getMinDate()),
                                    aggregationValue.getMaxValue(),
                                    DATE_FORMAT.format(aggregationValue.getMaxDate()),
                                };
                            tableModel.addRow(rowData);
                        }

                        // Visualisation -------------------------------------------
                        visualisationPanel.setParameters(parametersSet);
                        final VisualisationAction visualisationAction = new EprtrVisualisationAction(
                                installations,
                                visualisationPanel.getSelectedParameters(),
                                visualisationPanel);
                        visualisationPanel.setVisualisationAction(visualisationAction);

                        // Saved Configuration: Restore Export Parameters ----------
                        DefaultRendererConfigurationHelper.getInstance()
                                .restoreExportSettings(
                                    EprtrInstallationAggregationRenderer.this,
                                    jTabbedPane,
                                    parameterSelectionPanel,
                                    exportPanel,
                                    LOGGER);

                        // Saved Configuration: Restore selected Tab ---------------
                        DefaultRendererConfigurationHelper.getInstance()
                                .restoreSelectedTab(
                                    EprtrInstallationAggregationRenderer.class,
                                    jTabbedPane,
                                    LOGGER);
                    }
                };

            if (EventQueue.isDispatchThread()) {
                r.run();
            } else {
                EventQueue.invokeLater(r);
            }
        }
    }

    /**
     * DOCUMENT ME!
     */
    @Override
    public void dispose() {
        // mappingComponent.dispose();
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    @Override
    public String getTitle() {
        String desc = "";
        final Collection<CidsBean> beans = cidsBeans;
        if ((beans != null) && (beans.size() > 0)) {
            desc += beans.size() + " EPRTR Emittenten ausgewählt";
        }
        return desc;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  title  DOCUMENT ME!
     */
    @Override
    public void setTitle(final String title) {
    }

    @Override
    public void showExportPanel(final Collection<Parameter> selectedParameters) {
        EventQueue.invokeLater(new Runnable() {

                @Override
                public void run() {
                    parameterSelectionPanel.setSelectedParameters(selectedParameters);
                    jTabbedPane.setSelectedComponent(exportPanel);
                }
            });
    }
}
