/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.udm2020di.objectrenderer;

import de.cismet.cids.custom.udm2020di.AbstractCidsBeanRenderer;

/**
 * DOCUMENT ME!
 *
 * @author   Pascal Dihé <pascal.dihe@cismet.de>
 * @version  $Revision$, $Date$
 */
public class NamedAreaRenderer extends AbstractCidsBeanRenderer {

    //~ Instance fields --------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.cids.custom.udm2020di.widgets.MapPanel mapPanel;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form NamedAreaRenderer.
     */
    public NamedAreaRenderer() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        mapPanel = new de.cismet.cids.custom.udm2020di.widgets.MapPanel();

        setLayout(new java.awt.BorderLayout());

        mapPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        mapPanel.setPreferredSize(new java.awt.Dimension(600, 400));
        add(mapPanel, java.awt.BorderLayout.CENTER);
    } // </editor-fold>//GEN-END:initComponents

    @Override
    protected void init() {
        mapPanel.setCidsBean(cidsBean);
    }
}
